@startuml

interface Consts << interface >> {

}
class DatabaseProperties {

}
class Enemy {

}
class GameEndMenu {

}
class GameFrame {

}

class Main {

}
class MyDatabase {

}
class MyKeyAdapter {

}
class Player {

}
class PlayerPersistence {

}
class PropertiesFactory {

}
class RacingGameMenu {

}
class ResultsFrame {

}
class Road {

}
class TimeCount {

}
class TimeCountTest {

}
class insertBdTest {

}
class updateBdTest {

}

@enduml
