@startuml
actor Player
note right of Player: Игрок


Player -> Menu : запуск игры
note right of Menu: Меню игры

Menu ---> кнопка_Exit : выйти
Menu ---> кнопка_StartRacing : начать игру
Menu ---> кнопка_DeleteResultsDb : удалить результаты из бд
Menu ---> кнопка_ViewResultsDb : посмотреть результаты бд
кнопка_DeleteResultsDb --> MyDataBase
note right of Menu : Меню проверяет выбор пользователя

Menu --> Database : обновить данные в бд
note right of Database : База данных

Database --> Menu : данные в бд обновлены

@enduml